//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XLTGoods.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int ProId { get; set; }
        public string PName { get; set; }
        public string Brand { get; set; }
        public string Number { get; set; }
        public string Model { get; set; }
        public string OneCategory { get; set; }
        public string TwoCategory { get; set; }
    }
}
